spring:
  application:
    name: eureka-feign-client

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Feign的起步依赖中已经包含Hystrix依赖，所以只要在配置文件中开启Hystrix的功能就可以，不需要在pom文件再引入Hystrix
feign:
  hystrix:
    enabled: true